my_gaming_platform2/my_gaming_platform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task4.urls', namespace='task4')),
]

my_gaming_platform2/task4/urls.py
from django.urls import path
from . import views

app_name = 'task4'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('cart/', views.cart, name='cart'),
]

my_gaming_platform2/task4/views.py
from django.shortcuts import render

def index(request):
    context = {'title': 'Главная страница'}
    return render(request, 'fourth_task/index.html', context)

def shop(request):
    games = ['Atomic Heart', 'Cyberpunk 2077', 'Resident Evil 4']
    context = {'games': games}
    return render(request, 'fourth_task/shop.html', context)

def cart(request):
    games = []
    context = {'games': games}
    return render(request, 'fourth_task/cart.html', context)

my_gaming_platform2/templates/fourth_task/cart.html
{% extends 'fourth_task/menu.html' %}

{% block pagename %}Корзина{% endblock %}

{% block content %}
    <h1>Извините, ваша корзина пуста.</h1>
    <ul>
        {% for game in games %}
            <li>{{ game }}</li>
        {% endfor %}
    </ul>
{% endblock %}

my_gaming_platform2/templates/fourth_task/index.html
{% extends 'fourth_task/menu.html' %}
{% block pagename %}Главная страница{% endblock %}


my_gaming_platform2/templates/fourth_task/menu.html
<!DOCTYPE html>
<html>
<body>
    <div class="container">
        <h1>{% block pagename %}{% endblock %}</h1>
        <nav>
            {% block menu %}
                <ul>
                    <li><a href="{% url 'task4:index' %}">Главная</a></li>
                    <li><a href="{% url 'task4:shop' %}">Магазин</a></li>
                    <li><a href="{% url 'task4:cart' %}">Корзина</a></li>
                </ul>
            {% endblock %}
        </nav>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

my_gaming_platform2/templates/fourth_task/shop.html
{% extends 'fourth_task/menu.html' %}

{% block pagename %}Магазин{% endblock %}

{% block content %}
    <ul>
        {% for game in games %}
            <li>{{ game }}
                <button>Купить</button>
            </li>
        {% endfor %}
    </ul>
{% endblock %}